# Generated by Django 4.2.3 on 2023-07-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
