# Generated by Django 4.2.3 on 2023-08-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0002_variation'),
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='storeapp.variation'),
        ),
    ]
